networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana-data:
  mysql-data:

services:
  nestjs-app:
    build: ./nestjs-app
    container_name: nestjs-app
    working_dir: /app
    volumes:
      - ./nestjs-app:/app
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=nestjs_db
    command: sh -c "sleep 15 && npm run start:dev"
    networks:
      - monitoring

  mysql:
    image: mysql:5.7
    container_name: nestjs-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestjs_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=root --silent"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - monitoring

  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: nestjs-mysql-exporter
    environment:
      DATA_SOURCE_NAME: root:root@tcp(mysql:3306)/
    ports:
      - "9104:9104"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - monitoring

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nestjs-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - monitoring

  nestjs-prometheus:
    image: prom/prometheus:latest
    container_name: nestjs-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: nestjs-grafana
    ports:
      - "3001:3000"
    depends_on:
      - nestjs-prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
