networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana-data:
  mysql-data:

services:
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    command:
      - '--path.rootfs=/host'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro
    networks:
      - monitoring

  next-app:
    build: ./next-app
    container_name: next-app
    restart: always
    ports:
      - "80:3000"  # Map port 3000 in the container to port 80 on the host
    volumes:
      - ./next-app:/app
    depends_on:
      - nestjs-app
    environment:
      - NODE_ENV=production
    networks:
      - monitoring

  nestjs-app:
    build: ./nestjs-app
    container_name: nestjs-app
    working_dir: /app
    volumes:
      - ./nestjs-app:/app
    ports:
      - "3000:3000"
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_NAME=${DB_NAME}
    command: sh -c "sleep 15 && npm run start:dev"
    networks:
      - monitoring

  mysql:
    image: mysql:5.7
    container_name: nestjs-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u ${DB_USER} --password=${DB_PASSWORD} --silent"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - monitoring

  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: nestjs-mysql-exporter
    command: 
     - --config.my-cnf=/cfg/.my.cnf
    volumes:
      - "./.my.cnf:/cfg/.my.cnf"
    ports:
      - "9104:9104"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - monitoring

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nestjs-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - monitoring

  nestjs-prometheus:
    image: prom/prometheus:latest
    container_name: nestjs-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: nestjs-grafana
    ports:
      - "3001:3000"
    depends_on:
      - nestjs-prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
