global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "nestjs"
    metrics_path: /metrics
    static_configs:
      - targets: ["nestjs-app:3000"]

  - job_name: "mysql"
    static_configs:
      - targets: ["mysql-exporter:9104"]
