import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bail Service",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen`}>
        {/* Wrapper for the background */}
        <div className="relative min-h-screen">
          <div className="absolute inset-0 h-1/4 bg-gradient-to-r from-indigo-400 to-indigo-00" />

          <div className="absolute inset-0 top-1/4 h-3/4 bg-white" />

          <div className="relative z-10">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
